
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 10;
  public static final int NOTERMINAL = 7;
  public static final int PIPE = 6;
  public static final int EOL = 5;
  public static final int PROBVAL = 15;
  public static final int CONCAT = 14;
  public static final int EOF = 0;
  public static final int ARROW = 3;
  public static final int ONE_MORE = 13;
  public static final int ZERO_MORE = 12;
  public static final int IGNORE = 8;
  public static final int PROB = 4;
  public static final int error = 1;
  public static final int TERMINAL = 2;
  public static final int ZERO_ONE = 11;
  public static final int LPARENT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TERMINAL",
  "ARROW",
  "PROB",
  "EOL",
  "PIPE",
  "NOTERMINAL",
  "IGNORE",
  "LPARENT",
  "RPARENT",
  "ZERO_ONE",
  "ZERO_MORE",
  "ONE_MORE",
  "CONCAT",
  "PROBVAL"
  };
}

